### ISSUE TITLE
Cabal Support

### ISSUE THREAD

**Issue by emilypi** [ChrisPenner/lens-filesystem#1]
Hi Chris! I really like this library, but I'm not a frequent stack user. Would it be okay if opened a PR exposing + fixing up the cabal bounds? I have it ready to go if yes.

Additionally, I noticed your tests weren't running on Mac - our ls doesn't seem to return the directory in which files are contained, so those tests failed. I've added support for MacOS in the potential PR.

**Comment by emilypi** [comment]
Additionally, I noticed your tests weren't running on Mac - our `ls` doesn't seem to return the directory in which files are contained, so those tests failed. I've added support for MacOS in the potential PR.

**Comment by ChrisPenner** [comment]
Yes please go ahead and submit a PR; preferably separate PRs for the cabal vs test suite stuff.

I find it strange that the tests don't run for you since I also develop on MacOS; it's likely the Lib may have some slight differences between OS's anyways, so it's likely best to get it running on Linux and Mac on CI. I can probably do that tomorrow, but I'm interested to see what your fix is for the tests.

**Comment by emilypi** [comment]
Great, will do 😄

**Comment by ChrisPenner** [comment]
@emilypi 🤦‍♂ figured out the test failure problems; Git doesn't commit directories without files inside them, I added a test file inside so tests should be passing now 👍 

Still having a few issues with cross-platform symlinks though
